function Experiment = importxml(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EXPERIMENT = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  EXPERIMENT = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Experiment = importfile("/Volumes/Warwick/DRGS project/#518 4-26-24/SDH 2p/Final FOV/TimeLapse/#518_009/Experiment.xml", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Oct-2024 15:13:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "xmlVersion10";
opts.VariableTypes = "string";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "xmlVersion10", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "xmlVersion10", "EmptyFieldRule", "auto");

% Import the data
Experiment = readtable(filename, opts);

end